blocked-command-message:
  - "Unknown command. Type \"/help\" for help."

# Message that will receive those who has "abps.notify" permission
blocked-command-message-admin:
  - "&8[&cAntiPluginSteal&8] &fThe player &c{player} &ftried to execute a blocked command. (&c/{command}&f)"

# Blocked commands; You can add infinite amount of commands
blocked-commands:
  - "about"
  - "bukkit:about"
  - "bukkit:help"
  - "bukkit:?"
  - "bukkit:me"
  - "bukkit:pl"
  - "bukkit:plugins"
  - "bukkit:ver"
  - "bukkit:version"
  - "icanhasbukkit"
  - "info"
  - "?"
  - "/calc"
  - "/eval"
  - "//eval"
  - "//calc"
  - "calc"
  - "eval"
  - "pl"
  - "plugins"
  - "plugin"
  - "ver"
  - "version"
  - "bungee"
  - "lpx"
  - "tiolpxe"
  - "ncp"
  - "nocheatplus"
  - "spigotguard"
  - "ef"
  - "exploitfixer"
  - "intave"
  - "intaveac"
  - "iac"
  - "spartan"
  - "antiexploit"
